### ISSUE TITLE
Initial testing

### ISSUE THREAD

**Issue by panchocuetodaniel** [Arquisoft/viade_es4c#100]

**Comment by panchocuetodaniel** [comment]
Uploaded first version of tests focused on components

**Comment by CarlosMenchacaUO258650** [comment]
I need to log in into viade to complete some test but i ahd troubles. I search infromation and what i saw is that Jest doesn't give us tools to test that. I think we will need a framework to help us. "We will continue reporting"

**Comment by panchocuetodaniel** [comment]
Working on it
