### ISSUE TITLE
Expanding form of uploading routes

### ISSUE THREAD

**Issue by kriogenia** [Arquisoft/viade_es4c#111]
When an user uploads a route they should have the option to input a new name and description of the route.
This name and description should be included to the document that will be stored in the POD.

Optionally: it should let upload images and videos which will also be related to the route.

**Comment by kriogenia** [comment]
The form is now a modal pop-up and offers the inputs to add name and description, it still not add it to the route. I'll give you that part @TovarashiTwin. Hope you can do it when expanding the form to add the inputs you and @UO264637 need for the media part.

It is on the branch feature_improving_upload.

**Comment by kriogenia** [comment]
This issue close #103 
Its functionality is included in here.

**Comment by TovarashiTwin** [comment]
The name and description that you introduce in the modal now reflects in the route when you upload it

**Comment by kriogenia** [comment]
We close this, it's complete, the image loading will be looked at another issue
