### ISSUE TITLE
When loading routes and having shared the app crashes

### ISSUE THREAD

**Issue by kriogenia** [Arquisoft/viade_es4c#129]
`Uncaught (in promise) Error: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/rdf-dereference.json#mediatorRdfParseHandle mediated over all rejecting actors:`

IT reads three routes, two correct routes and one .txt

That's probably the bug.

**Comment by CarlosMenchacaUO258650** [comment]
I have made a quick fix. It shoulds work now

**Comment by kriogenia** [comment]
Perfect, everything works as expected now.
