### ISSUE TITLE
Improve Profile

### ISSUE THREAD

**Issue by kriogenia** [Arquisoft/viade_es4c#164]
Profile should be a card showing the profile name, image and pod link. It would be great if it showed the number of routes and friend routes of the user.

Friends of the Profile should be showed as cards with the name and link.

**Comment by kriogenia** [comment]
We should load the number of routes and friends routes to fill the profile, I trust on you for that matter @christianpe98

**Comment by christianpe98** [comment]
![](https://i.kym-cdn.com/photos/images/original/000/503/354/470.jpg)

**Comment by christianpe98** [comment]
Added functions to get number of routes and friends routes in 1c37a16, If there's anything wrong, let me know.

**Comment by kriogenia** [comment]
![image](https://user-images.githubusercontent.com/47500377/78674689-442e8f00-78e4-11ea-8d11-a4dbf5cf6db5.png)

That worked perfectly, thanks to that the profile card is complete. I'll finish the Friend Listing and we can call it a day with all the Profile improvements.

**Comment by kriogenia** [comment]
![image](https://user-images.githubusercontent.com/47500377/78678079-c751e400-78e8-11ea-973e-99d9a7e74134.png)

Aaaaand friend listing done, we did it. Profile page is now complete.
