### ISSUE TITLE
Beta users feedback

### ISSUE THREAD

**Issue by kriogenia** [Arquisoft/viade_es4c#209]
Hi,
if you are one of our beta testers please leave your feedback ahead, we really value your opinion.

Hola,
si eres uno de nuestro beta testes, por favor, deja aquí tu feedback. Valoramos mucho tu opinión.

**Comment by UO266575** [comment]
Me pidieron que probase la página debido a mi daltonismo, tengo protanopia y deuteranopia.
Después de probar un poco la aplicación todo parece funcionar bien. Subí un par de rutas que dibujé en la página que me dijeron aunque no subí ningún vídeo o imagen, pude ver todo perfectamente. El perfil también se ve bien, aunque no sé agregar amigos desde él. A pesar de mi daltonismo puede usar la aplicación sin ninguna dificultad. Buen trabajo.

**Comment by kriogenia** [comment]
I'm pasting here two anonymous inputs:

"Lo siento, de verdad que he intentado usar esta aplicación pero estoy perdida. Me registré en la web a la que me redirigieron pero cuando volví a la aplicación tenía que dar algunos permisos. No fui capaz, ni siquiera con las indicaciones que me dio la web."

"I'm sorry. I really tried to use this application but I'm kinda lost. I registered on the website they redirected me to but when I came back to the app I had to enable some permissions. I wasn't able to, even with the indications of the web".

---------------------------------

"Me registré, subí una ruta con un par de fotos y fui capaz de verla perfectamente! Pero el botón de Share está vacío, es posible que no funcione? No puedo compartirla por Twitter? Todo lo demás pintaba guay.

"I registered, upload a route with a couple of photos and I was able to see it perfectly. But the share button is empty, could it be that it doesn't work? Can't I share through Twitter? Everything else looked fine tho".

**Comment by AlbaSS18** [comment]
Inicié sesión y subí una ruta. Todo iba bien hasta que intenté ver las rutas que había subido. Fue en ese momento cuando me apareció un mensaje diciéndome que no había dado los permisos suficientes. Sin embargo, no fui capaz de cambiarlos. De todas maneras eso no me afectó y pude ver la ruta perfectamente. En la ruta sale el botón de clicar en los puntos inicio y final pero no hace nada. Debería quitarse la posibilidad de hacer clic o mostrar alguna opción. También sería interesante que aparecería información en el mapa y no al clicar el botón de points.
Decir también que estaría bien añadir un botón de cerrar cuando te sale el panel al subir una ruta

**Comment by Maarr** [comment]
Probé a registrarme, iniciar sesión y subir una ruta. En mis rutas estaba la ruta subida donde al hacer clic se visualiza bien, si es verdad que pulsé en los puntos de ubicación de la ruta pensando que hacían algo y no hacen nada. Pero por lo demás está bien, es intuitiva y amigable. 👍 👍

**Comment by UO263638** [comment]
Yo soy daltónico como Ton y probé la aplicación invitado por él. Quitando la molestia de tener que regresar a la aplicación y el problema de no saber como agregar a Ton como amigo, todo ha ido bien y como indicó él, la aplicación no me ha ocasionado ninguna dificultad de uso.
