### ISSUE TITLE
Edit routes

### ISSUE THREAD

**Issue by TovarashiTwin** [Arquisoft/viade_es4c#233]
Edit routes name and description, images and videos will be decided later

**Comment by kriogenia** [comment]
I will start trying to make a nice edit feature, if I'm able to do it correctly I'll let you know so you can handle the file reupload. The name and description component works with the RouteViade, so I'll make that it does edit it.

**Comment by kriogenia** [comment]
ShowRoutes on own routes now features a new and beautiful Edit button. When clicked makes the name and description modifiable. When Save persists the changes. You can start handling the pod side update.

**Comment by kriogenia** [comment]
Added an Upload component to ShowRoutes to handle the new media upload. It receives the route and its webId so I think it's all you need to make work.

So I leave this on you for the moment, when you implement the reuploads let me know. I think we'll need a way to reload the whole page to assert the changes when edit is made.

**Comment by TovarashiTwin** [comment]
the backend part is already fully funcional, waiting for a verification to close the issue

**Comment by csirgo** [comment]
Now images and videos can be added after uploading a route
