### ISSUE TITLE
Improvements after presentation

### ISSUE THREAD

**Issue by kriogenia** [Arquisoft/viade_es4c#236]
- Improved the documentation adding some info and the presentation diagrams
- Added "No media attached" image to routes without media
- Made the edit name and description functionality on the page showing routes (#233)
- Added the Upload media component on the page showing routes (#233)
- Implemented a way to add friends in the app (#238)
- Implemented the HashRoute to enable reloading (#243)
- Improved the code coverage by 15% (#244 #245)

**Comment by christianpe98** [comment]
- Added information message if there are routes on your POD that the app does not support
- Added information message if you try to accept a route that has already been shared with you
