### ISSUE TITLE
App Login and registry

### ISSUE THREAD

**Issue by christianpe98** [Arquisoft/viade_es4c#31]
Interesting links:
- https://github.com/pheyvaer/solid-chess
- https://github.com/solid/solid-auth-client
- https://github.com/inrupt/solid-react-sdk
- https://github.com/inrupt/solid-react-components

**Comment by christianpe98** [comment]
Documentation about folder structure in react,use of bootstrap,etc.
https://github.com/facebook/create-react-app/tree/master/docusaurus/docs

**Comment by kriogenia** [comment]
Implemented a BrowserRouter and protoype homepage and navbar in 5830bea440fd3f3643c502d794b610f9d3119de9

**Comment by christianpe98** [comment]
See 7341a103a85e90750a48d284196c68344a252d7b if there're errors with registry.
