### ISSUE TITLE
Define Route object

### ISSUE THREAD

**Issue by christianpe98** [Arquisoft/viade_es4c#68]
The application will work with abstractions of the user's routes. We must create a route object to decouple our application from the different route formats.

**Comment by christianpe98** [comment]
[RUTA]
-Nombre:String
-Descripcion(opcional):String
-Hitos:List<Hito>

[HITO]
-Nombre(opcional):String
-Descripcion(opcional):String
-Direccion(opcional):String
-Altitud(opcional):Double
-Latitud:Double
-Longitud:Double
-CodigoPostal(opcional):String

class RouteViade{
	constructor(name,items){
		this.name=name;
		this.description="";
		this.items=items;
	}
}

class ItemViade{
	constructor(latitude,longitude){
		this.latitude=latitude;
		this.longitude=longitude;
		this.name="";
		this.description="";
		this.address="";
		this.elevation=undefined;
		this.postalCode="";
	}
}

**Comment by UO264451** [comment]
After checking the final version of the RDF route specification, I propose to remove the address and postal code attributes from the Item entity, since they do not seem very useful when it comes to routes.

**Comment by kriogenia** [comment]
That's a good point. At first the item came to be looking at the options which gpx and geojson provide us, but looking carefully at the type of app we are building we probably won't need those fields, we should focus on the pure geographical ones.
Okay, I'm good with the change and will update the wiki if you implement the change.

**Comment by UO264451** [comment]
Perfect, i've fixed them. The pull request is pending.
