### ISSUE TITLE
Display selected Route

### ISSUE THREAD

**Issue by kriogenia** [Arquisoft/viade_es4c#88]
When the client selects a route, it should be properly displayed on the ShowRoute page. This issue encapsulates and relates #35 and #73

**Comment by kriogenia** [comment]
Modified the ShowRoute page to display the route it receives as parameter through its state from MyRoutes in commit b8f832265e3b635bf83976ab68dafffbcd18a5e4

**Comment by kriogenia** [comment]
I'm using the feature_show_full_route branch. 
@CarlosMenchacaUO258650 I placed a dummy route in your page to try it, it works fine and it shows you how you should send the route to the page to display it

TBD, protect /showRoute from direct access as it doesn't work without a route

**Comment by CarlosMenchacaUO258650** [comment]
I moved that Route to the parser RDF -> Route.

**Comment by kriogenia** [comment]
Completed, it also displays friend routes
