### ISSUE TITLE
Document RouteViade

### ISSUE THREAD

**Issue by kriogenia** [Arquisoft/viade_es4c#89]
Add to the wiki all the info regarding the RouteViade, it is the key point of the app.

**Comment by kriogenia** [comment]
ViadeRoute and ViadeItem structure explained on the wiki. It still lacks its related parsers: @UO264451 @christianpe98 

Can you take care of that?

**Comment by TovarashiTwin** [comment]
Documentation needs to be updated with better diagrams and fix the images routes
