### ISSUE TITLE
Solid cant parse our ttl file that we upload

### ISSUE THREAD

**Issue by TovarashiTwin** [Arquisoft/viade_es4c#94]
Carmen and I changed stringbuilder to string becouse the parsed failed when being executed.
The upload feature is almost implemented in develop, so you can test your parser with your own pod.
Right now when you open the uploaded file in solid it displays a fetch/parser error, so probably is because the format that parser to rdf returns isnt correct.

**Comment by UO264451** [comment]
Ok, I think I have solved it, I have created a pull request for it.
