### ISSUE TITLE
The register option doesnt redirect back

### ISSUE THREAD

**Issue by TovarashiTwin** [Arquisoft/viade_es4c#99]
If you register, or even log in through the register option, with the button in the top nav it doesnt redirect you back to our aplication.

**Comment by kriogenia** [comment]
We make the register through external providers so we are redirecting them to their pages, we can't control the user the moment we sent them there. In the future if we implement our own pod servers we can at least guarantee the redirect from that registration.
This looks like a WNF for me, let's close the issue for now and if we make the alternative we can probably give it another look.
